create table if not exists public.sitara_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source text not null,
  name text not null,
  phone text not null,
  city text,
  interest text,
  message text,
  page_url text,
  status text not null default 'new'
);

alter table public.sitara_leads enable row level security;

create policy "Allow public lead inserts"
on public.sitara_leads
for insert
to anon
with check (true);
